### PR TITLE
Bump ruby to 3.0.3

### PR DESCRIPTION
**Pull request by chvp**

### CODE REVIEW

**Review by bmesuere — COMMENTED** [review]
I probably also asked with the previous update, but doesn't this also require an ansible update?

**Comment by chvp** [comment]
Ah yes, that also needs to happen.

**Comment by chvp** [comment]
https://github.com/dodona-edu/dodona-ansible/pull/121

**Comment by bmesuere** [comment]
@jorg-vr this PR should be updated to be able to merge this next week. A deploy must then happen in concert with a server-side ruby upgrade.

**Review by bmesuere — APPROVED** [review]
There are a number of gems that are bumped. Was this by accident or part of the Ruby bump?

**Comment by bmesuere** [comment]
Pinging @chvp for approval since review doesn't work.

**Comment by jorg-vr** [comment]
@bmesuere  they seem to be caused by my last commit. I ran `bundle install` and `bundle update`, should I avoid bundle update?

**Comment by chvp** [comment]
`bundle update` is generally not necessary, since dependabot updates our dependencies for us. Changes look good to me.

**Pull request merged**
