### PR TITLE
No-wrap metrics

### PR DESCRIPTION
**Pull request by beardhatcode**
This pull request ads no-wrap to the metrics

### CODE REVIEW

**Comment by beardhatcode** [comment]
An alternative for the `text-nowrap` is using col-sm-12 for the sumbissions

**Comment by beardhatcode** [comment]
```

**Comment by beardhatcode** [comment]
woeps

**Review by beardhatcode — COMMENTED** [review]
`no-wrap` instead of `text-center`

**Comment by bmesuere** [comment]
Note to self: add some top and bottom margin before merging. Things are too close together on smallest display size.

**Review by bmesuere — APPROVED** [review]

**Review by chvp — APPROVED** [review]

**Pull request merged**
