### PR TITLE
Add test server to our infrastructure

### PR DESCRIPTION
**Pull request by bmesuere**
This pull request adds a new environment to our infrastructure. This new test environment will be deployed to mestra.ugent.be and will contain feature branches in combination with a seeded database. This branch is automatically deployed when a review is requested on a PR or when the 'deploy' label is assigned. The action automatically removes the label when done. In a later phase, scripted tests to this environment could be added.

- [x] Manually install mestra
- [x] Manually deploy to mestra using capistrano
- [x] Reseed the database after each deploy
- [x] Properly set up a rails environment for the server. hostname? secrets? (@chvp can you help with this?)
- [x] Deploy a fixed branch using GH actions
- [x] Enable GH "environments"
- [x] Deploy a dynamic branch using GH actions
- [x] Enable deploy by label
- [x] Properly install mestra using ansible (@rien?)

### CODE REVIEW

**Comment by bmesuere** [comment]
test

**Comment by bmesuere** [comment]
deploy

**Comment by bmesuere** [comment]
test comment

**Comment by bmesuere** [comment]
@rien What is the status of the ansible part? Can this branch be merged?

**Review by rien — APPROVED** [review]

**Pull request merged**
