### PR TITLE
Fix average dot of violin plot being placed outside of the graph when it is high

### LINKED ISSUE #3206: Average dot outside of graph
The average dot  of the 'Number of submissions per user' plot is placed outside the graph when the average is larger than 20.

image

### PR DESCRIPTION
**Pull request by tibdhond**
This pull request fixes the bug where the average dot of the violin graph is outside of the graph when the average is larger than 20.
image

Closes #3206 .

### CODE REVIEW

**Review by bmesuere — APPROVED** [review]

**Review by niknetniko — APPROVED** [review]

**Review by chvp — COMMENTED** [review]
I have a slight concern that it won't be immediately obvious that the average is (in some cases much) higher than 20.

**Comment by tibdhond** [comment]
> I have a slight concern that it won't be immediately obvious that the average is (in some cases much) higher than 20.

How about if we replace the dot with a simple arrow (something like '>') when the average is outside of the graph?

**Comment by chvp** [comment]
Trying a different icon seems like a good idea. Can you post a screenshot if you try that? I would definitely mention the average in a tooltip if that is not already the case.

**Comment by tibdhond** [comment]
I was thinking of something like this:

image

**Review by bmesuere — CHANGES_REQUESTED** [review]
I'm not sure if I like the icon for 20+ (but can live with it).

I would change the tick mark on the axis from "20" to "20+", this will also be more correct for the violin plot itself.

**Review by bmesuere — APPROVED** [review]

**Review by chvp — APPROVED** [review]

**Pull request merged**
