### PR TITLE
Fix infinite progress bar when filtering students in an evaluation

### LINKED ISSUE #4918: Evaluation search acts as if it keeps searching
When searching for a student in an evaluation, the search indicator keeps spinning even after the search has completed.

image

### PR DESCRIPTION
**Pull request by jorg-vr**
Closes #4918

### CODE REVIEW

**Review by bmesuere — COMMENTED** [review]
This feels a bit like a hack. Why isn't the element present in the first place?

**Comment by jorg-vr** [comment]
It is context depended. If there is scoring present, there will be a tab with scores of users.
If no scoring is made, this tab is not present. Which makes this feature crash.

If you prefer I can probably also fix this by a rails template check? (But that risks an edge case where the tab was not present before, but should be present now, which could create a bug....)

**Comment by jorg-vr** [comment]
The issue is very similar to #4996

**Review by niknetniko — CHANGES_REQUESTED** [review]
I we want to fix this like this (I have no opinion), could we do only one `querySelector`?

**Review by niknetniko — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]

**Pull request merged**
