### PR TITLE
Small refactor in questions

### PR DESCRIPTION
**Pull request by niknetniko**
This pull request address [this comment](https://github.com/dodona-edu/dodona/pull/2094#discussion_r488618617) on the original PR, by incorporating the `question_state` changes into the `update` action.

### CODE REVIEW

**Review by charvp — COMMENTED** [review]
I feel like things could be simpler if you use the record in the `permitted_attributes_for_update` method. Did you try this?

**Comment by niknetniko** [comment]
> I feel like things could be simpler if you use the record in the `permitted_attributes_for_update` method. Did you try this?

Unless I'm missing something, do you mean something like this?

```ruby
def update?
  return false if record.answered?

  super || user.course_admin?(record.submission.course)
end

def permitted_attributes_for_update
  if transitioning? and transition?(record.transition_to, record.transition_from)
    %i[question_state]
  else
    super
  end
end
```

Some more thoughts:

- The `transition?` function is useful as a standalone function to be able to check if the question can transition to a specific state (which is used in the question table and in the json builder).
- The `transition_from` is useful to detect if the question is still in the expected state
- The `transition_to` is needed because you can't access the params in the policy

**Comment by charvp** [comment]
> > I feel like things could be simpler if you use the record in the `permitted_attributes_for_update` method. Did you try this?
> 
> Unless I'm missing something, do you mean something like this?
> 
> <snip>

That is what I meant indeed. Looking at it with a fresh perspective though, I guess you lose the ability to tell the user that their update failed with that construction? That is something that would be nice to have I think.

**Comment by niknetniko** [comment]
> I guess you lose the ability to tell the user that their update failed with that construction

Just tried it, and that's exactly what happens. This behaviour is currently used to notify the user if the question was already changed by someone else, so it seems useful to keep it.

**Review by charvp — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]

**Pull request merged**
