### PR TITLE
Disable CSRF protection for API requests

### LINKED ISSUE #1765: InvalidAuthenticityToken when changing series description via API
When trying to modify a series description via the API, I'm getting an error message. The server crashes on `An ActionController::InvalidAuthenticityToken occured in series#update` (you've all had the mails). AFAIK, I wouldn't need an authenticity token when using the API.

My exact request:

```sh
token="..."
series="..."
curl -s \
        -H "Accept: application/json" \
        -H "Authorization: $token" \
        --data '_method=patch' \
        --data-urlencode 'series[description]=test' \
        "https://naos.ugent.be/nl/series/$series/"
```

I've also tried this in a more complex manner, taking the authenticity token from a previous request while reusing those cookies:

```sh
token="..."
series="..."
cookie="$(mktemp)"

request() {
        url="$1"
        shift
        curl -s -H "Authorization: $token" "$@" "https://naos.ugent.be/$url"
}

csrf="$(request "series/$series/" --cookie-jar "$cookie" | sed -n 's_.*<meta name="csrf-token" content="\([^"]*\)" />.*_\1_p')"

request "series/$series/" \
        --cookie "$cookie" \
        -H 'Authority: naos.ugent.be' \
        -H 'Origin: https://naos.ugent.be' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -H "Referer: https://naos.ugent.be/nl/series/$series/edit/" \
        -H 'Accept-Encoding: gzip, deflate, br' \
        -H 'Accept: application/json' \
        -H 'X-Requested-With: XMLHttpRequest' \
        -H "X-CSRF-Token: $csrf" \
        --data '_method=patch' \
        --data-urlencode "authenticity_token=$csrf" \
        --data-urlencode 'series%5Bdescription%5D=test' \
        --compressed

rm "$cookie"
```

This results in the same error, but more readable, so I'll post it here:

```
ActionController::InvalidAuthenticityToken in SeriesController#update

ActionController::InvalidAuthenticityToken
Extracted source (around line #217):

#215
#216         def handle_unverified_request
*217           raise ActionController::InvalidAuthenticityToken
#218         end
#219       end
#220     end

Extracted source (around line #249):

#247
#248       def handle_unverified_request # :doc:
*249         forgery_protection_strategy.new(self).handle_unverified_request
#250       end
#251
#252       #:nodoc:

Extracted source (around line #255):

#253       # clear run strategies and remove cached variables.
#254       def handle_unverified_request
*255         super # call the default behaviour which resets/nullifies/raises
#256         request.env["devise.skip_storage"] = true
#257         sign_out_all_scopes(false)
#258       end


Rails.root: /home/dodona/rails/releases/20200226102415

Framework Trace
actionpack (6.0.2.1) lib/action_controller/metal/request_forgery_protection.rb:217:in `handle_unverified_request'
actionpack (6.0.2.1) lib/action_controller/metal/request_forgery_protection.rb:249:in `handle_unverified_request'
devise (4.7.1) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
actionpack (6.0.2.1) lib/action_controller/metal/request_forgery_protection.rb:244:in `verify_authenticity_token'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:429:in `block in make_lambda'
...

Request parameters
{"_method"=>"patch",
 "authenticity_token"=>"612YeWJb0lcerLHlwzDrz3sPbbQSRszuqGp8DwVEkytoucIKqVTBj7IZ449JtcPZ2NapkzAR0ETm7OPrVBR2EA==",
 "series"=>{"description"=>"test"},
 "id"=>"259"}

Session dump
_csrf_token: "dhf8uqux4+5lV280RwjIKYzfREOd/QN6QDRqAbuG9hA="
session_id: "63e7a2f3a32c1bd33a5cdbaa1970db41"

Env dump
HTTP_ACCEPT: "application/json"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ORIGIN: "https://naos.ugent.be"
HTTP_VERSION: "HTTP/1.1"
HTTP_X_CSRF_TOKEN: "612YeWJb0lcerLHlwzDrz3sPbbQSRszuqGp8DwVEkytoucIKqVTBj7IZ449JtcPZ2NapkzAR0ETm7OPrVBR2EA=="
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "78.47.31.148"
SERVER_NAME: "naos.ugent.be"
SERVER_PROTOCOL: "HTTP/1.1"

Response headers
None
```

### PR DESCRIPTION
**Pull request by thepieterdc**
This pull request disables CSRF protection for API requests, as discussed in #1765. My latest reply in that issue contains the reason as to why the current implementation is used.

- [x] Tests were added.

Closes #1765.

### CODE REVIEW

**Comment by charvp** [comment]
I'm not sure this is the way we want to fix this. Wouldn't this open us up to CSRF attacks? If another website makes a JSON request they would be able to masquerade as a user without any user input right?

**Comment by rien** [comment]
Maybe it's possible to add a [skip_forgery_protection](https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-skip_forgery_protection) to the `look_for_token` method?

If not, it's maybe a solution to have a
```
skip_before_action :verify_authenticity_token, if: :token_authenticated?
```
Where `token_authenticated` would use some value set by `look_for_token`.

**Comment by thepieterdc** [comment]
> Maybe it's possible to add a [skip_forgery_protection](https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-skip_forgery_protection) to the `look_for_token` method?

This is not possible, `skip_forgery_protection` cannot be called from within an instance method.

> If not, it's maybe a solution would be to have a
> 
> ```ruby
> skip_before_action :verify_authenticity_token, if: :token_authenticated?
> ```
> 
> Where `token_authenticated` would use some value set by `look_for_token`.

This also turns out to be impossible, since `skip_before_action`s are always executed before `before_action` is evaluated.

**Comment by thepieterdc** [comment]
Another possible solution, although this results in limited extensibility and is thus not 100% future proof:

```ruby
skip_before_action :verify_authenticity_token, if: :look_for_token?`
```
where `look_for_token?` returns a boolean on successful authentication.

**Comment by rien** [comment]
Great! I there are some `skip_before_action :verify_authenticity_token` which are obsolete now.

**Comment by bmesuere** [comment]
@thepieterdc the other skips can indeed be removed

**Comment by thepieterdc** [comment]
> @thepieterdc the other skips can indeed be removed

> Great! I think there are some `skip_before_action :verify_authenticity_token` which are obsolete now.

Done :)

**Pull request merged**
