### PR TITLE
Add a setting to courses to allow registration with personal accounts

### PR DESCRIPTION
**Pull request by jorg-vr**
This pull request is a replacement of #3752. It introduces a single extra toggle option to allow personal users to register for a course.

image

It is not very clear to me how this separate setting should interact with `open_for_institution`. Right now I take a union: everyone in this institution or without an institution. But this is an odd combination which I do not expect to see in practice.

- [x] Tests were added

Part of https://github.com/dodona-edu/dodona/issues/2597

### CODE REVIEW

**Review by niknetniko — APPROVED** [review]
Code looks good :+1: 

I assume there are good reasons to have a toggle and not another level (as was done in #3752), but this does mean users can create potentially weird situations. For example, if registration is `open_for_institution`, but personal accounts are enabled, this is functionally the same as `open_for_all`, as users can trivially create a personal account. (This is not really actionable, just a thought)

**Review by bmesuere — CHANGES_REQUESTED** [review]
@niknetniko @jorg-vr As far as I'm aware (but I could be wrong), the direct "secret" link could be used to bypass the general settings. This is something we don't want for personal accounts: a teacher sharing the direct course link doesn't want students with personal accounts.

The toggle should be a checkbox. According to the spec, toggles are used for instantaneous actions.

We have been calling this "personal accounts" internally, but that might not be the best name to use in the application. In a way, all accounts are personal since they are not group accounts. "private accounts" might be a better name and including gmail and microsoft in the toggle/checkbox text might also help with making this more clear.

**Comment by jorg-vr** [comment]
@bmesuere the secret is only there to bypass who can see the course. It does not bypass registration.

The setting introduced in this pr only changes who can register for a course. If you are not allowed to register, this is also impossible with a secret. (I included this case in the tests)

I will edit the checkbox and the text

**Comment by jorg-vr** [comment]
Closed in favor of https://github.com/dodona-edu/dodona/pull/3752

**Pull request closed without merging**
