### PR TITLE
Improvements to institution management

### PR DESCRIPTION
**Pull request by niknetniko**
Part of #2452, implements two of the suggestions:

- Adds pagination & search to institution page
- Better default names for institutions
   - Smartschool: subdomain (e.g. `name` in `[name].smartschool.be`)
   - GSuite: the domain itself (e.g. `example.com`)
   - Office365: the domain of the email of the user
   - Others (LTI, Saml): no change
   
- [x] Tests were added

### CODE REVIEW

**Review by bmesuere — COMMENTED** [review]
Do we need an additional boolean to indicate that an automatic name is currently used instead of a manual one? Otherwise it will be hard to find which ones might need an update?

**Comment by chvp** [comment]
> Do we need an additional boolean to indicate that an automatic name is currently used instead of a manual one? Otherwise it will be hard to find which ones might need an update?

Agreed. This should also allow the sort to be done by that column first, allowing the custom SQL to be dropped. We should probably mark all institutions with the current default name with this boolean as well.

**Comment by niknetniko** [comment]
Applied suggestions:

- By default, the `generated_name` column is `true`.
- Existing institutions with the default name are also `true`
- When the name is edited, the column becomes `false`.

I've also added an icon to indicate a generated name:
image

**Review by bmesuere — APPROVED** [review]
At least for g suite and smartschool it should be possible to convert the existing n/a's to a more meaningful name.

**Comment by niknetniko** [comment]
> At least for g suite and smartschool it should be possible to convert the existing n/a's to a more meaningful name.

Do you mean this should be added as a migration to this PR? Or is this something for a future PR?

**Review by chvp — CHANGES_REQUESTED** [review]
For sign in, we currently decide whether or not to show institutions based on whether their name is equal to the default name. This should be changed.

I would do the migration @bmesuere mentioned in this PR.

**Review by chvp — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]
🚢

**Pull request merged**
